name: 🚀 Deploy Front (Vite, dist only)

on:
  push:
    branches: [main]
    paths:
      - "package.json"
      - "package-lock.json"
      - "vite.config.*"
      - "src/"
      - "public/"

concurrency:
  group: deploy-front
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🟢 Node 18 + npm cache
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: package-lock.json

      - name: 🛠 Build
        run: |
          npm ci --prefer-offline --no-audit --no-fund
          npm run build  # создаст dist/

      - name: 📦 Rsync dist → server
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -az --delete
          path: dist/
          remote_path: /edu-talks/        # твоя текущая папка на сервере (не меняем)
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_KEY }}

      # Если SPA раздаётся через pm2 serve — оставь шаг; если nginx — удали
      - name: 🔁 (Опционально) pm2 reload
        if: ${{ success() }}
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            pm2 reload edutalks || true